### ISSUE TITLE
Add build and deployment of Ansible, Go, and Helm Memcached operators

### ISSUE THREAD

**Issue by geerlingguy** [geerlingguy/operator-sdk-performance-testing#1]
See: https://github.com/operator-framework/operator-sdk-samples

Basically, for each one we need a registry available. Maybe I could set up a public registry in Quay, or set up a separate private registry in CI?

Then we need to cd into the respective directory and run the commands as instructed in the respective READMEs.

**Comment by geerlingguy** [comment]
Maybe use https://ttl.sh ?

**Comment by geerlingguy** [comment]
My PR is running into this issue: https://github.com/operator-framework/operator-sdk/issues/3335

Might be a directory pathing thing. Might also be related to https://github.com/operator-framework/operator-sdk/issues/2648

**Comment by geerlingguy** [comment]
Updated to the 1.0.0 versions, but still getting:

```
...
Step 3/6 : RUN ansible-galaxy collection install -r ${HOME}/requirements.yml  && chmod -R ug+rwx ${HOME}/.ansible
 ---> Running in 345df6571084\n
ERROR! Unexpected Exception, this is probably a bug: [Errno 13] Permission denied: '/opt/ansible/requirements.yml'
to see the full traceback, use -vvv
Makefile:42: recipe for target 'docker-build' failed
```

Edit: to fix, I made the clonse of the examples repo 777 :P

**Comment by geerlingguy** [comment]
Now working on building the Go operator and getting it up and running, but hitting:

```
unable to recognize "STDIN": no matches for kind "Certificate" in version "cert-manager.io/v1alpha2"
unable to recognize "STDIN": no matches for kind "Issuer" in version "cert-manager.io/v1alpha2"
make: *** [deploy] Error 1
```

**Comment by geerlingguy** [comment]
Now the Helm memcached operator deploy is giving:

```
error: unable to recognize "STDIN": no matches for kind "ServiceMonitor" in version "monitoring.coreos.com/v1"
make: *** [deploy] Error 1
```

Looks like we have to add in extra stuff for the Helm operator sample :P

**Comment by geerlingguy** [comment]
Trying to deploy prometheus-operator results in:

```
pods "prometheus-operator-7589597769-" is forbidden: error looking up service account default/prometheus-operator: serviceaccount "prometheus-operator" not found
```

**Comment by geerlingguy** [comment]
I had to manually create the ServiceAccount prior to deploying the operator (I guess since the ServiceAccount definition is way down at the end of the manifest, so it's not created in time).

```yaml
# Without this the operator doesn't deploy successfully on the first go.
- name: Manually create the prometheus-operator ServiceAccount.
  k8s:
    state: present
    definition:
      apiVersion: v1
      kind: ServiceAccount
      metadata:
        labels:
          app.kubernetes.io/component: controller
          app.kubernetes.io/name: prometheus-operator
          app.kubernetes.io/version: v0.41.1
        name: prometheus-operator
        namespace: default
```
