### ISSUE TITLE
Benchmark how long it takes to tear down 15 CRs

### ISSUE THREAD

**Issue by geerlingguy** [geerlingguy/operator-sdk-performance-testing#11]
Following up on #3 and #4, I would like to see how long it takes to delete all 15 CRs and have all the memcached pods go away. Basically the inverse of #3, but run this benchmark after #4.

## My MacBook Pro i9

| Operator Type | Run 1 | Run 2 | Run 3 | Average |
| --- | --- | --- | --- | --- |
| Ansible | 23.69s | 23.85s | 17.94s | **21.83s** |
| Go | 17.61s | 17.64s | 17.51s | **17.59s** |
| Helm | 23.33s | 23.89s | 23.49s | **23.57s** |

## GitHub Actions CI

| Operator Type | Run 1 | Run 2 | Run 3 | Average |
| --- | --- | --- | --- | --- |
| Ansible | 18.09s | 17.86s | 17.98s | **17.98s** |
| Go | 17.56s | 17.64s | 17.62s | **17.61s** |
| Helm | 18.09s | 18.16s | 18.08s | **18.11s** |

## Amazon EC2 (`m5.large`, 200GB gp2 volume)

| Operator Type | Run 1 | Run 2 | Run 3 | Average |
| --- | --- | --- | --- | --- |
| Ansible | 17.97s | 23.63s | 18.03s | **19.88s** |
| Go | 17.60s | 17.47s | 17.35s | **17.47s** |
| Helm | 23.33s | 23.21s | 23.32s | **23.29s** |

**Comment by geerlingguy** [comment]
Should be as simple as:

```yaml
- name: Un-deploy {{ memcached_cr_count }} {{ operator_type }} memcached CRs.
  k8s:
    state: absent
    definition: "{{ lookup('template', 'templates/memcached-cr.yml.j2') }}"

- name: B3 Wait for all {{ operator_type }} Memcached Pods to be gone.
  k8s_info:
    api_version: v1
    kind: Pod
    label_selectors:
      - "{{ app_label_selector }}"
  register: memcached_pods
  until: (memcached_pods.resources | count) == 0
  delay: 5
  retries: 120
```
