### ISSUE TITLE
Benchmark how long it takes for 15 new CRs to be reconciled

### ISSUE THREAD

**Issue by geerlingguy** [geerlingguy/operator-sdk-performance-testing#3]
This is the first and most basic performance test.

I want to see, for each operator type, how long it takes after creating 25 memcached instances (CRs), for the CRs to be reconciled.

**Comment by geerlingguy** [comment]
These results are from my local computer, running in Kind, with each scenario on its own, with `memcached_cr_count: 15`:

| Operator Type | Run 1 | Run 2 | Run 3 | Average |
| --- | --- | --- | --- | --- |
| Ansible | 20.99s | 20.52s | 20.28s | **20.60s** |
| Go | 9.68s | 9.20s | 9.14s | **9.34s** |
| Helm | 51.81s | 63.68s | 60.33s | **58.61s** |

Local computer in Minikube:

| Operator Type | Run 1 | Run 2 | Run 3 | Average |
| --- | --- | --- | --- | --- |
| Ansible | 25.34s | 31.01s | 30.90s | **29.08s** |
| Go | 9.50s | 9.99s | 9.90s | **9.80s** |
| Helm | 39.46s | 38.70s | 46.92s | **41.69s** |

And in GitHub Actions, doing the same:

| Operator Type | Run 1 | Run 2 | Run 3 | Average |
| --- | --- | --- | --- | --- |
| Ansible | 67.17s | 66.72s | 66.20s | **66.70s** |
| Go | 10.51s | 9.54s | 10.07s | **10.04s** |
| Helm | 33.60s | 35.28s | 38.49s | **35.79s** |

And finally, in a Kind instance running in AWS (`m5.large`, 200GB gp2 volume):

| Operator Type | Run 1 | Run 2 | Run 3 | Average |
| --- | --- | --- | --- | --- |
| Ansible | 85.95s | 85.94s | 85.61s | **85.83s** |
| Go | 8.65s | 9.05s | 9.10s | **8.93s** |
| Helm | 39.32s | 37.04s | 42.06s | **39.47s** |

**Comment by geerlingguy** [comment]
A couple things I'm running into:

1. I can't figure out any way with Go operator samples to see a status field that changes once it finishes its reconciliation.
2. Each of the three operators has a slightly different default CR (Helm's being wildly different):

    - go: https://github.com/operator-framework/operator-sdk-samples/blob/master/go/memcached-operator/config/samples/cache_v1alpha1_memcached.yaml
    - ansible: https://github.com/operator-framework/operator-sdk-samples/blob/master/ansible/memcached-operator/config/samples/cache_v1alpha1_memcached.yaml
    - helm: https://github.com/operator-framework/operator-sdk-samples/blob/master/helm/memcached-operator/config/samples/cache_v1alpha1_memcached.yaml

**Comment by geerlingguy** [comment]
I was using the following for Ansible:

```yaml
# For Ansible, wait for reconciliation to update to 'Success'.
- name: Wait for {{ operator_type }} Memcached reconciliation to complete.
  k8s_info:
    api_version: cache.example.com/v1alpha1
    kind: Memcached
    name: "{{ 'memcached-%02x' | format(item) }}"
    namespace: default
  register: memcacheds
  failed_when: false
  when: operator_type == 'ansible'
  until: memcached_pod.resources[0].status.conditions[0].reason == 'Successful'
  delay: 3
  retries: 60
  loop: "{{ range(0, memcached_cr_count) | list }}"
```

But to be a little more fair with comparing the operators, I'm going to do a different test for the amount of time everything takes to be ready—since Go's Status field on the Memcached resource behaves differently, and in some cases never appears on the resource even if the managed Pod is ready and running...

  1. Wait for there to be as many memcached pods running as are expected.
  2. Wait for all the pods to be 'Ready' using `kubectl wait`. I was trying to figure out a way to do it with Ansible directly, but I couldn't, so I reopened this issue I had opened a while back: https://github.com/ansible-collections/community.kubernetes/issues/18
